<?php
namespace includes\classes;

class ProjectCategory extends TaxonomyType {
	public function getName() {
		return 'cat-project';
	}

	public function getObjectRelate() {
		return 'project';
	}

	public function getConfigs() {
		$labels = array(
			'name'              => _x( 'Categories', 'taxonomy general name', 'dm' ),
			'singular_name'     => _x( 'Categories', 'taxonomy singular name', 'dm' ),
			'search_items'      => __( 'Search Category', 'dm' ),
			'all_items'         => __( 'All Categories', 'dm' ),
			'parent_item'       => __( 'Parent Category', 'dm' ),
			'parent_item_colon' => __( 'Parent Category:', 'dm' ),
			'edit_item'         => __( 'Edit Category', 'dm' ),
			'update_item'       => __( 'Update Category', 'dm' ),
			'add_new_item'      => __( 'Add New Category', 'dm' ),
			'new_item_name'     => __( 'New Category Name', 'dm' ),
			'menu_name'         => __( 'Categories', 'dm' ),
		);

		$args = array(
			'hierarchical'      => true,
			'labels'            => $labels,
			'show_ui'           => true,
			'show_admin_column' => true,
			'query_var'         => true,
			'rewrite'           => array( 'slug' => 'cat-project' ),
		);
		return array_merge(parent::getConfigs(), $args); // TODO: Change the autogenerated stub
	}
}